env: development

redis:
  host: 192.168.230.53
  port: 6379
  database: 48

profile:
  c3p0:
    initialPoolSize: 5
    minPoolSize: 5
    maxPoolSize: 30

spring:
  data:
    mongodb:
      uri: mongodb://dev_mdb_e_enroll:4510055612dY@172.24.133.23:34001,172.24.133.24:34001,172.24.133.25:34001/dev_mdb_e_enroll?autoConnectRetry:true
  rabbitmq:
    listener: auto-startup:true
    addresses: 192.168.9.78:5672
    username: cloud                                                 `
    password: cloud
    virtual-host: elearning_dev

uc:
  client:
    login:
      name: auxoexam
      password: 3e21a657519a831aa1b4717e9ff94c3d

waf:
  uc:
    uri: https://ucbetapi.101.com/v0.93/
  http:
    uri: http://uc-personal-web.beta.web.sdp.101.com/v0.9/
  exception:
    friendly:
      disabled: true
      remote:
        httpstatus:
          proxy: false
  trace:
    enabled: false
  debug:
    enabled: false
  security:
    disabled: false

gaea:
  cookie:
    path:
      level: 0
    maxAge: -1

elearning:
  api:
    java:
      url: http://e.api.java.test100.huayu.nd
  java:
    service:
      url: http://elearning-service.dev.web.nd
  learning-unit:
    url: http://elearning-learning-unit.dev.web.nd

auxo:
  enroll:
    url: http://elearning-enroll-api.dev.web.nd
  cloud:
    url: http://test.cloud.91open.huayu.nd
  message:
    url: http://auxo-message-service.dev.web.nd

cs:
  service:
    host: sdpcs.beta.web.sdp.101.com
    id: 17df3f76-d7bb-4798-a869-5befffff056b
    name: dev_content_huayu_cs
  download:
    url: http://sdpcs.beta.web.sdp.101.com/v0.1/static
  s3:
    isAws: false
	
cssdk:
  cs:
    host: sdpcs.beta.web.sdp.101.com
  s3:
    isAws: false 




