waf:
  unAuthenticated: /,/index.jsp,/hotfix/**,/schedule/**
  enableAppIdFilter: false

gaea:
  auth:
    redirectDisabled: true

spring:
  data:
    mongodb:
      uri: mongodb://dev_mdb_e_enroll:4510055612dY@172.24.133.23:34001,172.24.133.24:34001,172.24.133.25:34001/dev_mdb_e_enroll?autoConnectRetry:true
  rabbitmq:
    listener: auto-startup:true
    addresses: 192.168.9.78:5672
    username: cloud                                                 `
    password: cloud
    virtual-host: elearning_dev
	
redis:
  host: 192.168.230.53
  port: 6379
  database: 48